# Generated by Django 5.2 on 2025-04-16 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('support_pdf', models.FileField(blank=True, null=True, upload_to='supports/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('duree', models.IntegerField(blank=True, help_text='Durée en heures', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('formateur', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormationRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription_au_formation', models.DateField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.modules'),
        ),
    ]
